# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Norske Folkeeventyr
# email: contact@pikselert.com
description: Norske folkeeventyr for barn og voksne
# baseurl: ""
# url: "https://folkeeventyr.no"
permalink: /:title/


destination: /Users/henrik/Sites/folkeeventyr-staging

highlighter: none
# incremental: true
# safe: true
strict_front_matter: true


# Build settings
# markdown: kramdown

collections:
  images:
    output: true
    permalink: /images/:path

plugins:
- jekyll-paginate

tag_page_layout: tag_index
tag_page_dir: tag

# https://jch.penibelst.de
compress_html:
  clippings: all
  comments: all
  startings: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false