# Site settings
title: Norske Folkeeventyr
# email: contact@pikselert.com
description: Norske folkeeventyr for barn og voksne
# baseurl: ""
# url: "https://folkeeventyr.no"
permalink: /:title/

highlighter: none
incremental: false
safe: true
strict_front_matter: true


# Build settings
# markdown: kramdown

collections:
  images:
    output: true
    permalink: /images/:path

# plugins:
# - jekyll-paginate

tag_page_layout: tag_index
tag_page_dir: tag